# Generated by Django 6.0.5 on 2026-06-10 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('usuarios', '0002_remove_usuario_clave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_prestamo', models.DateField(verbose_name='Fecha de préstamo')),
                ('f_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de devolución')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipos.equipo', verbose_name='Equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-f_prestamo', '-id'],
            },
        ),
    ]
