# Generated by Django 6.0.5 on 2026-06-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('empresa', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('asunto', models.CharField(choices=[('demo', 'Solicitar Demo'), ('info', 'Solicitar Información'), ('soporte', 'Soporte Técnico'), ('otro', 'Otro')], max_length=20, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Contacto landing',
                'verbose_name_plural': 'Contactos landing',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
