# Generated by Django 6.0.5 on 2026-06-10 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de baja')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_baja', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Registro de baja',
                'verbose_name_plural': 'Registros de baja',
                'ordering': ['-fecha_baja'],
            },
        ),
    ]
