# Generated by Django 6.0.5 on 2026-06-10 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('piso', models.IntegerField(choices=[(1, 'Primer Piso'), (2, 'Segundo Piso'), (3, 'Tercer Piso')], verbose_name='Piso')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['piso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EquipoDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencias.dependencia', verbose_name='Dependencia')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Equipo en dependencia',
                'verbose_name_plural': 'Equipos en dependencias',
                'unique_together': {('equipo', 'dependencia')},
            },
        ),
    ]
