# Generated by Django 6.0.5 on 2026-06-10 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ninv', models.CharField(max_length=50, verbose_name='N° Inventario')),
                ('nserie', models.CharField(max_length=50, unique=True, verbose_name='N° Serie')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('fondos', models.CharField(max_length=100, verbose_name='Fondos')),
                ('estado', models.IntegerField(choices=[(0, 'Activo'), (1, 'De baja')], default=0, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categorias.categoria', verbose_name='Categoría')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['id'],
            },
        ),
    ]
